# Generated by Django 3.0 on 2020-05-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='comntent',
            new_name='content',
        ),
    ]
